# Grid environment
environment: GRID
grid_width: 100
grid_height: 100

# Graph environment
#environment: SMALL_WORLD
#num_cells: 1000
#output_degree: 6
#p: 0.1

# Used to compute the agent count
occupation_rate: 0.5

# Number of steps to execute
num_steps: 100

# Cell utility distribution policy: UNIFORM, LINEAR, INVERSE or STEP
utility: LINEAR

# Defines Agent interactions type: LOCAL or SMALL_WORLD
agent_interactions: LOCAL

# BenchmarkCells node weight
cell_weight: 1.
# If enabled, update weight of edges between cells (CELL_SUCCESSORs) according
# to the count of agents currently located in the cell
dynamic_cell_edge_weights: false

cell_interactions: NONE
sync_mode: HARD_SYNC_MODE
cell_size: 16

# BenchmarkAgents node weight
agent_weight: 1.

# Period at which a new contact is created from the local neighborhood
refresh_local_contacts: 10
# Period at which agents create contacts among their contacts
refresh_distant_contacts: 1

MetaAgentBase:
  # Move policy: RANDOM or MAX
  move_policy: MAX
  # Perception range size
  range_size: 1
  # Contact edges weight
  contact_weight: 1.
  # Max contacts count
  max_contacts: 10

# If utility is not UNIFORM, defines a list of attractors.
# An attractor is defined as [[x, y], radius]
attractors: 
  - [[20, 20], 100]
  - [[80, 80], 100]


# Test cases list
# A Test case is defined as [ALGORITHM, [lb_periods, ...]]
# Available algorithms:
# SCHEDULED_LB, ZOLTAN_LB, GRID_LB, ZOLTAN_CELL_LB, RANDOM_LB
test_cases:
  - [SCHEDULED_LB, [10, 50]]
  - [ZOLTAN_LB, [1, 10, 50]]
  - [GRID_LB, [1, 10]]
  - [ZOLTAN_CELL_LB, [1, 10, 50]]
  - [RANDOM_LB, [50]]

json_output: false
dot_output: false
